const S={user:null,config:null};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function tg(){return window.Telegram?.WebApp?.initDataUnsafe?.user||null}function ref(){const p=new URLSearchParams(location.search);return p.get('ref')||p.get('startapp')||''}async function api(u,o={}){const h={'Content-Type':'application/json',...(o.headers||{})};if(S.user?.id)h['x-user-id']=S.user.id;const r=await fetch(u,{...o,headers:h}),d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||'Request failed');return d}function money(n){return '$'+Number(n||0).toFixed(2)}function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function render(){const u=S.user;$('#balance').textContent=money(u.balance);$('#pending').textContent=money(u.pending_balance);$('#hillscoin').textContent=Number(u.hillscoin||0).toFixed(2)+' HBC';$('#lifetime').textContent=money((u.balance||0)+(u.pending_balance||0));$('#refCode').textContent=u.referral_code||'—';$('#name').textContent=[u.first_name,u.last_name].filter(Boolean).join(' ')||'User';$('#username').textContent=u.username?'@'+u.username:'Telegram user';$('#avatar').textContent=(u.first_name||'H')[0].toUpperCase();$('#tgid').textContent=u.telegram_id||'Browser demo';$('#email').value=u.email||'';$('#address').value=u.payment_address||'';$('#withdrawAddress').value=u.payment_address||'';$('#available').textContent=money(u.balance)}
async function auth(){S.user=(await api('/api/auth',{method:'POST',body:JSON.stringify({telegramUser:tg(),referral:ref()})})).user;S.config=(await api('/api/config'));render()}
function page(n){$$('.page').forEach(x=>x.classList.toggle('active',x.id===n));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===n));if(n==='tasks')tasks();if(n==='history')history();render();scrollTo(0,0)}
async function tasks(){const d=await api('/api/tasks');$('#taskList').innerHTML=d.tasks.map(t=>`<article class="card task"><div class="tasktop"><div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p></div><b class="reward">+$${Number(t.reward).toFixed(2)}</b></div><div class="actions"><a class="secondary" href="${safe(t.url)}" target="_blank" rel="noopener">Open</a><button class="${t.completed?'secondary':'primary'}" ${t.completed?'disabled':''} onclick="complete(${t.id})">${t.completed?'Completed':'Complete'}</button></div></article>`).join('')||'<div class="card">No tasks available.</div>'}async function complete(id){try{const d=await api('/api/tasks/'+id+'/complete',{method:'POST',body:'{}'});S.user=d.user;render();toast('Task reward added');tasks()}catch(e){toast(e.message)}}
async function history(){const d=await api('/api/transactions');$('#historyList').innerHTML=d.transactions.map(t=>{const p=['task_reward','referral_bonus'].includes(t.type);return `<div class="row"><span><b>${esc(t.note||t.type)}</b><small>${esc(t.created_at)}</small></span><b class="${p?'plus':'minus'}">${p?'+':'-'}${Number(t.amount).toFixed(2)} ${esc(t.currency)}</b></div>`}).join('')||'<div>No transactions yet.</div>'}
async function refresh(){S.user=(await api('/api/me')).user;render()}async function save(e){e.preventDefault();try{S.user=(await api('/api/profile',{method:'PATCH',body:JSON.stringify({email:$('#email').value.trim(),paymentAddress:$('#address').value.trim()})})).user;render();toast('Profile saved')}catch(e){toast(e.message)}}async function verify(){try{await api('/api/email/verify-demo',{method:'POST',body:'{}'});await refresh();toast('Email verified in demo mode')}catch(e){toast(e.message)}}async function withdraw(e){e.preventDefault();const m=$('#withdrawMsg');try{const d=await api('/api/withdraw',{method:'POST',body:JSON.stringify({amount:Number($('#amount').value),paymentAddress:$('#withdrawAddress').value.trim()})});await refresh();m.textContent=d.message;m.classList.remove('hidden');$('#amount').value=''}catch(e){m.textContent=e.message;m.classList.remove('hidden')}}async function copy(){const link=S.config.botUsername?`https://t.me/${S.config.botUsername}?startapp=ref_${S.user.referral_code}`:`${location.origin}/?ref=${S.user.referral_code}`;try{await navigator.clipboard.writeText(link);toast('Referral link copied')}catch{toast(link)}}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function safe(u){try{const x=new URL(u,location.origin);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}}
$$('[data-page]').forEach(x=>x.onclick=()=>page(x.dataset.page));$('#refresh').onclick=async()=>{try{await refresh();toast('Updated')}catch(e){toast(e.message)}};$('#profileForm').onsubmit=save;$('#verify').onclick=verify;$('#withdrawForm').onsubmit=withdraw;$('#copy').onclick=copy;(async()=>{try{if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand()}await auth();await tasks()}catch(e){console.error(e);toast(e.message)}})();
