require('dotenv').config();
const express=require('express');const path=require('path');const crypto=require('crypto');const fs=require('fs');const Database=require('better-sqlite3');
const app=express(),PORT=Number(process.env.PORT||3000),ADMIN_KEY=process.env.ADMIN_KEY||'change-me',BOT_USERNAME=process.env.BOT_USERNAME||'';
app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));
if(!fs.existsSync(path.join(__dirname,'data')))fs.mkdirSync(path.join(__dirname,'data'),{recursive:true});
const db=new Database(path.join(__dirname,'data','hillsbyte.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,telegram_id TEXT UNIQUE,username TEXT,first_name TEXT,last_name TEXT,email TEXT,email_verified INTEGER DEFAULT 0,balance REAL DEFAULT 0,pending_balance REAL DEFAULT 0,hillscoin REAL DEFAULT 0,referral_code TEXT UNIQUE,referred_by INTEGER,payment_address TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',reward REAL NOT NULL,reward_coin TEXT DEFAULT 'USD',url TEXT DEFAULT '#',active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS completions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,task_id INTEGER NOT NULL,status TEXT DEFAULT 'completed',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,task_id));
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount REAL NOT NULL,payment_address TEXT NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL,currency TEXT DEFAULT 'USD',note TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(db.prepare('SELECT COUNT(*) n FROM tasks').get().n===0){const i=db.prepare('INSERT INTO tasks(title,description,reward,reward_coin,url) VALUES(?,?,?,?,?)');[['Welcome Task','Open the task page and follow its instructions.',.25,'USD','https://example.com'],['HillsByte Starter','Read the campaign information.',.10,'USD','https://example.com'],['Community Task','Visit the campaign page.',.15,'USD','https://example.com']].forEach(x=>i.run(...x));}
function ref(){let c;do c='HB'+crypto.randomBytes(4).toString('hex').toUpperCase();while(db.prepare('SELECT 1 FROM users WHERE referral_code=?').get(c));return c;}
function reqUser(req){const id=String(req.header('x-user-id')||'');return id?db.prepare('SELECT * FROM users WHERE id=?').get(id):null;}
function createUser(t,r){let u=t.id?db.prepare('SELECT * FROM users WHERE telegram_id=?').get(String(t.id)):null;if(u)return u;let rb=null;if(r){const x=db.prepare('SELECT id FROM users WHERE referral_code=?').get(String(r).replace(/^ref_/i,'').toUpperCase());if(x)rb=x.id;}const q=db.prepare('INSERT INTO users(telegram_id,username,first_name,last_name,referral_code,referred_by) VALUES(?,?,?,?,?,?)').run(t.id?String(t.id):'demo-'+crypto.randomUUID(),t.username||'demo_user',t.first_name||'Demo',t.last_name||'User',ref(),rb);if(rb){db.prepare('UPDATE users SET hillscoin=hillscoin+1 WHERE id=?').run(rb);db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'referral_bonus',1,'HBC','Referral signup bonus')").run(rb);}return db.prepare('SELECT * FROM users WHERE id=?').get(q.lastInsertRowid);}
app.post('/api/auth',(req,res)=>{try{res.json({ok:true,user:createUser(req.body?.telegramUser||{},req.body?.referral||'')});}catch(e){console.error(e);res.status(500).json({ok:false,error:'Authentication failed'});}});
app.get('/api/me',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});res.json({ok:true,user:u});});
app.patch('/api/profile',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const e=req.body?.email,a=req.body?.paymentAddress;if(e!==undefined&&String(e).length>160)return res.status(400).json({ok:false,error:'Email is too long'});if(a!==undefined&&String(a).length>120)return res.status(400).json({ok:false,error:'Payment address is too long'});db.prepare('UPDATE users SET email=COALESCE(?,email),payment_address=COALESCE(?,payment_address) WHERE id=?').run(e??null,a??null,u.id);res.json({ok:true,user:db.prepare('SELECT * FROM users WHERE id=?').get(u.id)});});
app.post('/api/email/verify-demo',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});if(!u.email)return res.status(400).json({ok:false,error:'Add an email first'});db.prepare('UPDATE users SET email_verified=1 WHERE id=?').run(u.id);res.json({ok:true});});
app.get('/api/tasks',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});res.json({ok:true,tasks:db.prepare('SELECT t.id,t.title,t.description,t.reward,t.reward_coin,t.url,CASE WHEN c.id IS NULL THEN 0 ELSE 1 END completed FROM tasks t LEFT JOIN completions c ON c.task_id=t.id AND c.user_id=? WHERE t.active=1 ORDER BY t.id DESC').all(u.id)});});
app.post('/api/tasks/:id/complete',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const t=db.prepare('SELECT * FROM tasks WHERE id=? AND active=1').get(req.params.id);if(!t)return res.status(404).json({ok:false,error:'Task not found'});if(db.prepare('SELECT 1 FROM completions WHERE user_id=? AND task_id=?').get(u.id,t.id))return res.status(409).json({ok:false,error:'Task already completed'});const tx=db.transaction(()=>{db.prepare("INSERT INTO completions(user_id,task_id,status) VALUES(?,?,'completed')").run(u.id,t.id);db.prepare('UPDATE users SET balance=balance+? WHERE id=?').run(t.reward,u.id);db.prepare('INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,?,?,?,?)').run(u.id,'task_reward',t.reward,t.reward_coin,t.title);});tx();res.json({ok:true,user:db.prepare('SELECT * FROM users WHERE id=?').get(u.id)});});
app.get('/api/transactions',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});res.json({ok:true,transactions:db.prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 100').all(u.id)});});
app.post('/api/withdraw',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const amount=Number(req.body?.amount),address=String(req.body?.paymentAddress||u.payment_address||'').trim();if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({ok:false,error:'Invalid withdrawal amount'});if(!/^0x[a-fA-F0-9]{40}$/.test(address))return res.status(400).json({ok:false,error:'Enter a valid BEP20-compatible EVM address'});if(amount<1)return res.status(400).json({ok:false,error:'Minimum withdrawal is $1 in this starter'});if(amount>u.balance)return res.status(400).json({ok:false,error:'Insufficient available balance'});const tx=db.transaction(()=>{db.prepare('UPDATE users SET balance=balance-?,payment_address=? WHERE id=?').run(amount,address,u.id);db.prepare('INSERT INTO withdrawals(user_id,amount,payment_address) VALUES(?,?,?)').run(u.id,amount,address);db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'withdrawal',?,'USD','Withdrawal request')").run(u.id,amount);});tx();res.json({ok:true,message:'Withdrawal request submitted'});});
function admin(req,res,next){if(req.header('x-admin-key')!==ADMIN_KEY)return res.status(403).json({ok:false,error:'Forbidden'});next();}
app.get('/api/admin/overview',admin,(req,res)=>res.json({ok:true,users:db.prepare('SELECT COUNT(*) n FROM users').get().n,pendingWithdrawals:db.prepare("SELECT COUNT(*) n FROM withdrawals WHERE status='pending'").get().n,paidWithdrawals:db.prepare("SELECT COALESCE(SUM(amount),0) total FROM withdrawals WHERE status='paid'").get().total}));
app.get('/api/admin/withdrawals',admin,(req,res)=>res.json({ok:true,withdrawals:db.prepare('SELECT w.*,u.username,u.telegram_id FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC LIMIT 200').all()}));
app.post('/api/admin/withdrawals/:id/status',admin,(req,res)=>{const s=String(req.body?.status||'');if(!['pending','paid','rejected'].includes(s))return res.status(400).json({ok:false,error:'Invalid status'});db.prepare('UPDATE withdrawals SET status=? WHERE id=?').run(s,req.params.id);res.json({ok:true});});
app.get('/api/config',(req,res)=>res.json({ok:true,botUsername:BOT_USERNAME,appUrl:process.env.APP_URL||''}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log('HillsByte running on http://localhost:'+PORT));
