require('dotenv').config();
const express=require('express');const path=require('path');const crypto=require('crypto');const fs=require('fs');const Database=require('better-sqlite3');
const app=express();const PORT=Number(process.env.PORT||3000);const ADMIN_KEY=String(process.env.ADMIN_KEY||'change-me');const BOT_USERNAME=String(process.env.BOT_USERNAME||'');
app.use(express.json({limit:'5mb'}));app.use(express.urlencoded({extended:false,limit:'5mb'}));app.use(express.static(__dirname));
const dataDir=path.join(__dirname,'data');if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});
const db=new Database(path.join(dataDir,'hillsbyte.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,telegram_id TEXT UNIQUE,username TEXT,first_name TEXT,last_name TEXT,email TEXT,email_verified INTEGER DEFAULT 0,balance REAL DEFAULT 0,pending_balance REAL DEFAULT 0,hillscoin REAL DEFAULT 0,referral_code TEXT UNIQUE,referred_by INTEGER,payment_address TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',reward REAL NOT NULL,reward_coin TEXT DEFAULT 'USD',url TEXT DEFAULT '#',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS completions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,task_id INTEGER NOT NULL,status TEXT DEFAULT 'pending',proof TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount REAL NOT NULL,payment_address TEXT NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL,currency TEXT DEFAULT 'USD',note TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
function col(t,c){return db.prepare(`PRAGMA table_info(${t})`).all().some(x=>x.name===c)} if(!col('completions','proof'))db.prepare("ALTER TABLE completions ADD COLUMN proof TEXT DEFAULT ''").run();
if(db.prepare('SELECT COUNT(*) n FROM tasks').get().n===0){const s=db.prepare('INSERT INTO tasks(title,description,reward,reward_coin,url,active) VALUES(?,?,?,?,?,1)');s.run('Welcome Task','Open the task and follow the instructions.',.25,'USD','https://example.com');s.run('Community Task','Visit the campaign page and complete the required action.',.15,'USD','https://example.com')}
function referral(){let x;do{x='HB'+crypto.randomBytes(4).toString('hex').toUpperCase()}while(db.prepare('SELECT id FROM users WHERE referral_code=?').get(x));return x}
function user(id){return db.prepare('SELECT * FROM users WHERE id=?').get(id)}
function reqUser(req){const id=String(req.get('x-user-id')||'');return id?user(id):null}
function bep(a){return /^0x[a-fA-F0-9]{40}$/.test(a)}
function createUser(t={},ref=''){if(t.id){const e=db.prepare('SELECT * FROM users WHERE telegram_id=?').get(String(t.id));if(e)return e}let rb=null;const rc=String(ref||'').replace(/^ref_/i,'').replace(/^startapp_/i,'').trim().toUpperCase();if(rc){const r=db.prepare('SELECT id FROM users WHERE referral_code=?').get(rc);if(r)rb=r.id}const tid=t.id?String(t.id):'demo-'+crypto.randomUUID();const r=db.prepare('INSERT INTO users(telegram_id,username,first_name,last_name,referral_code,referred_by) VALUES(?,?,?,?,?,?)').run(tid,String(t.username||'demo_user').slice(0,100),String(t.first_name||'Demo').slice(0,100),String(t.last_name||'User').slice(0,100),referral(),rb);if(rb){db.prepare('UPDATE users SET hillscoin=hillscoin+1 WHERE id=?').run(rb);db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'referral_bonus',1,'HBC','Referral signup bonus')").run(rb)}return user(r.lastInsertRowid)}
app.post('/api/auth',(req,res)=>{try{res.json({ok:true,user:createUser(req.body?.telegramUser||{},req.body?.referral||'')})}catch(e){console.error(e);res.status(500).json({ok:false,error:'Authentication failed'})}});
app.get('/api/me',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});res.json({ok:true,user:u})});
app.patch('/api/profile',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const email=req.body.email!==undefined?String(req.body.email).trim():null;const pa=req.body.paymentAddress!==undefined?String(req.body.paymentAddress).trim():null;if(pa&&!bep(pa))return res.status(400).json({ok:false,error:'Enter a valid BEP20 address'});db.prepare('UPDATE users SET email=COALESCE(?,email),payment_address=COALESCE(?,payment_address) WHERE id=?').run(email,pa,u.id);res.json({ok:true,user:user(u.id)})});
app.post('/api/email/verify-demo',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});if(!u.email)return res.status(400).json({ok:false,error:'Add an email first'});db.prepare('UPDATE users SET email_verified=1 WHERE id=?').run(u.id);res.json({ok:true,user:user(u.id)})});
app.get('/api/tasks',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const tasks=db.prepare(`SELECT t.*,COALESCE((SELECT c.status FROM completions c WHERE c.user_id=? AND c.task_id=t.id ORDER BY c.id DESC LIMIT 1),'available') status,CASE WHEN EXISTS(SELECT 1 FROM completions c WHERE c.user_id=? AND c.task_id=t.id AND c.status='approved') THEN 1 ELSE 0 END completed FROM tasks t WHERE t.active=1 ORDER BY t.id DESC`).all(u.id,u.id);res.json({ok:true,tasks})});
app.post('/api/tasks/:id/submit',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const t=db.prepare('SELECT * FROM tasks WHERE id=? AND active=1').get(req.params.id);if(!t)return res.status(404).json({ok:false,error:'Task not found'});const proof=String(req.body?.proof||'').trim();if(!proof)return res.status(400).json({ok:false,error:'Screenshot proof is required'});const e=db.prepare('SELECT * FROM completions WHERE user_id=? AND task_id=? ORDER BY id DESC LIMIT 1').get(u.id,t.id);if(e?.status==='pending')return res.status(409).json({ok:false,error:'Already pending review'});if(e?.status==='approved')return res.status(409).json({ok:false,error:'Already approved'});if(e?.status==='rejected'){db.prepare("UPDATE completions SET status='pending',proof=?,created_at=CURRENT_TIMESTAMP WHERE id=?").run(proof,e.id)}else db.prepare("INSERT INTO completions(user_id,task_id,status,proof) VALUES(?,?,'pending',?)").run(u.id,t.id,proof);res.json({ok:true,message:'Proof submitted for review'})});
app.get('/api/transactions',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});res.json({ok:true,transactions:db.prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 100').all(u.id)})});
app.post('/api/withdraw',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({ok:false,error:'Not authenticated'});const amount=Number(req.body?.amount),address=String(req.body?.paymentAddress||u.payment_address||'').trim();if(!Number.isFinite(amount)||amount<1)return res.status(400).json({ok:false,error:'Minimum withdrawal is $1'});if(!bep(address))return res.status(400).json({ok:false,error:'Enter a valid BEP20 address'});if(amount>u.balance)return res.status(400).json({ok:false,error:'Insufficient available balance'});try{const id=db.transaction(()=>{const x=db.prepare('UPDATE users SET balance=balance-?,payment_address=? WHERE id=? AND balance>=?').run(amount,address,u.id,amount);if(x.changes!==1)throw Error('balance');const w=db.prepare("INSERT INTO withdrawals(user_id,amount,payment_address,status) VALUES(?,?,?,'pending')").run(u.id,amount,address);db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'withdrawal',?,'USD','Withdrawal request')").run(u.id,amount);return w.lastInsertRowid})();res.json({ok:true,withdrawalId:id})}catch(e){res.status(500).json({ok:false,error:'Unable to create withdrawal'})}});
function admin(req,res,next){if(String(req.get('x-admin-key')||'')!==ADMIN_KEY)return res.status(403).json({ok:false,error:'Forbidden'});next()}
app.get('/api/admin/overview',admin,(req,res)=>{res.json({ok:true,users:db.prepare('SELECT COUNT(*) n FROM users').get().n,tasks:db.prepare('SELECT COUNT(*) n FROM tasks').get().n,activeTasks:db.prepare('SELECT COUNT(*) n FROM tasks WHERE active=1').get().n,pendingWithdrawals:db.prepare("SELECT COUNT(*) n FROM withdrawals WHERE status='pending'").get().n,pendingSubmissions:db.prepare("SELECT COUNT(*) n FROM completions WHERE status='pending'").get().n})});
app.get('/api/admin/tasks',admin,(req,res)=>res.json({ok:true,tasks:db.prepare('SELECT * FROM tasks ORDER BY id DESC').all()}));
app.post('/api/admin/tasks',admin,(req,res)=>{const title=String(req.body?.title||'').trim(),description=String(req.body?.description||'').trim(),url=String(req.body?.url||'#').trim(),reward=Number(req.body?.reward),coin=String(req.body?.reward_coin||req.body?.rewardCoin||'USD');if(!title||!Number.isFinite(reward)||reward<=0)return res.status(400).json({ok:false,error:'Title and valid reward required'});const r=db.prepare('INSERT INTO tasks(title,description,reward,reward_coin,url,active) VALUES(?,?,?,?,?,?)').run(title,description,reward,coin,url,req.body?.active===false?0:1);res.json({ok:true,task:db.prepare('SELECT * FROM tasks WHERE id=?').get(r.lastInsertRowid)})});
app.patch('/api/admin/tasks/:id',admin,(req,res)=>{const id=Number(req.params.id),e=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);if(!e)return res.status(404).json({ok:false,error:'Task not found'});const title=req.body.title!==undefined?String(req.body.title).trim():e.title,description=req.body.description!==undefined?String(req.body.description).trim():e.description,url=req.body.url!==undefined?String(req.body.url).trim():e.url,reward=req.body.reward!==undefined?Number(req.body.reward):e.reward,coin=req.body.reward_coin!==undefined?String(req.body.reward_coin):e.reward_coin,active=req.body.active!==undefined?(req.body.active?1:0):e.active;if(!title||!Number.isFinite(reward)||reward<=0)return res.status(400).json({ok:false,error:'Invalid task'});db.prepare('UPDATE tasks SET title=?,description=?,reward=?,reward_coin=?,url=?,active=? WHERE id=?').run(title,description,reward,coin,url||'#',active,id);res.json({ok:true,task:db.prepare('SELECT * FROM tasks WHERE id=?').get(id)})});
app.post('/api/admin/tasks/:id/toggle',admin,(req,res)=>{const id=Number(req.params.id),e=db.prepare('SELECT * FROM tasks WHERE id=?').get(id);if(!e)return res.status(404).json({ok:false,error:'Task not found'});const a=e.active?0:1;db.prepare('UPDATE tasks SET active=? WHERE id=?').run(a,id);res.json({ok:true,active:a})});
app.delete('/api/admin/tasks/:id',admin,(req,res)=>{const id=Number(req.params.id);db.prepare('DELETE FROM completions WHERE task_id=?').run(id);const r=db.prepare('DELETE FROM tasks WHERE id=?').run(id);res.json({ok:r.changes>0})});
app.get('/api/admin/task-submissions',admin,(req,res)=>res.json({ok:true,submissions:db.prepare(`SELECT c.*,t.title task_title,t.reward,t.reward_coin,u.username,u.first_name,u.last_name,u.telegram_id FROM completions c JOIN tasks t ON t.id=c.task_id JOIN users u ON u.id=c.user_id ORDER BY c.id DESC LIMIT 500`).all()}));
app.post('/api/admin/task-submissions/:id/status',admin,(req,res)=>{const id=Number(req.params.id),status=String(req.body?.status||'').toLowerCase();const s=db.prepare(`SELECT c.*,t.title,t.reward,t.reward_coin FROM completions c JOIN tasks t ON t.id=c.task_id WHERE c.id=?`).get(id);if(!s||s.status!=='pending'||!['approved','rejected'].includes(status))return res.status(400).json({ok:false,error:'Invalid submission/status'});db.transaction(()=>{db.prepare('UPDATE completions SET status=? WHERE id=?').run(status,id);if(status==='approved'){if(String(s.reward_coin).toUpperCase()==='HBC')db.prepare('UPDATE users SET hillscoin=hillscoin+? WHERE id=?').run(s.reward,s.user_id);else db.prepare('UPDATE users SET balance=balance+? WHERE id=?').run(s.reward,s.user_id);db.prepare('INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(? ,\'task_reward\',?,?,?)').run(s.user_id,s.reward,s.reward_coin,'Approved task: '+s.title)}})();res.json({ok:true,status})});
app.get('/api/admin/withdrawals',admin,(req,res)=>res.json({ok:true,withdrawals:db.prepare(`SELECT w.*,u.username,u.first_name,u.last_name,u.telegram_id FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC LIMIT 500`).all()}));
app.post('/api/admin/withdrawals/:id/status',admin,(req,res)=>{const id=Number(req.params.id),status=String(req.body?.status||'').toLowerCase(),w=db.prepare('SELECT * FROM withdrawals WHERE id=?').get(id);if(!w||w.status!=='pending'||!['paid','rejected'].includes(status))return res.status(400).json({ok:false,error:'Invalid withdrawal/status'});db.transaction(()=>{db.prepare('UPDATE withdrawals SET status=? WHERE id=?').run(status,id);if(status==='rejected'){db.prepare('UPDATE users SET balance=balance+? WHERE id=?').run(w.amount,w.user_id);db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'withdrawal_refund',?,'USD','Rejected withdrawal refunded')").run(w.user_id,w.amount)}else db.prepare("INSERT INTO transactions(user_id,type,amount,currency,note) VALUES(?,'withdrawal_paid',?,'USD','Withdrawal marked paid')").run(w.user_id,w.amount)})();res.json({ok:true,status})});
app.get('/api/config',(req,res)=>res.json({ok:true,bot_username:BOT_USERNAME,botUsername:BOT_USERNAME,min_withdrawal:1}));app.get('/api/health',(req,res)=>res.json({ok:true,service:'HillsByte',timestamp:new Date().toISOString()}));
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({ok:false,error:'API endpoint not found'});res.sendFile(path.join(__dirname,'index.html'))});
app.listen(PORT,'0.0.0.0',()=>console.log(`HillsByte server running on port ${PORT}`));
